### ISSUE TITLE
Doesnt seem to work

### ISSUE THREAD

**Issue by NadTests** [YoinkedYoink/ai-aim#1]
when i execute ai aimbot.py then choose the best.pt model and go on arsenal it doesnt lock on the color or anything

**Comment by YoinkedYoink** [comment]
If you are using the default python ide, does it show fps in the window or does it just close?

Secondly, have you changed the player outline to pink like it says in the readme?

Lastly, make sure you are holding the key you set for the aimbot. It's not a toggle, but the triggerbot is a toggle.

If you want to see if it's just an issue with the model then enable the gui in the file.

**Comment by YoinkedYoink** [comment]
If you are unsure about the keybinds, everything is in the .py file. And you can change the binds to your liking.![image](https://github.com/YoinkedYoink/ai-aim/assets/87105685/043f27cb-e133-4d56-a0aa-37a27c7708e9)

**Comment by YoinkedYoink** [comment]
I'mma close this in 2 days because of no response.

**Comment by NadTests** [comment]
sorry yeah u can close it, it works now

**Comment by YoinkedYoink** [comment]
:ok_hand:
